### ISSUE TITLE
Context should be part of the factory object 

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#1001] opened 2021-08-31 13:54 UTC
## Description

We seem to create context directly in commands. This typically should be done thru factory that will allow us to measure some extra metrics/analytics etc.

**Comment by craicoverflow** [comment] 2021-08-31 13:56
Removing bug label as this is not a bug, it is just something not implemented.

Agreed though - or would it make sense to have it be part of `Connection`?

**Comment by wtrocki** [comment] 2021-08-31 13:57
It would not be used only for the networking side. 

As for labels. I always get them assigned by default and forget to remove them :D sorry.

**Comment by craicoverflow** [comment] 2021-08-31 13:58
Ack 😄 

You need to choose "blank issue" or "Feedback", not the "Bug template".

**Comment by alexal** [comment] 2021-09-08 18:33
@wtrocki assign this to me, please.

**Comment by craicoverflow** [comment] 2021-09-08 19:12
> Agreed though - or would it make sense to have it be part of Connection?

The reason I mentioned this was because there is a special OAuth context that is available which attaches Bearer tokens to every request. I think we can ignore that for now though.

**Closed** 2021-09-09 15:35 UTC
Labels: Tech debt, priority/important-longterm
