### ISSUE TITLE
Add a style guide to ensure consistency across the CLI

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#641] opened 2021-05-05 13:54 UTC
The project needs to have a style guide developed which should be used as a reference when developing new commands, and in the future new services. This should cover everything from naming patterns, flags, error handling and more.

https://clig.dev/ is a great example of a general CLI guideline which this CLI followed in parts.

**Comment by wtrocki** [comment] 2021-09-29 13:24
This sounds like duplicate of set of the existing issues.

**Closed by wtrocki** 2021-09-29 13:24 UTC
Labels: documentation
